In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Classification/Diabetes_Data.csv"
data = pd.read_csv(url)
data

     Age  Weight  BloodSugar Gender  Diabetes
0     25     119       130.8     男生         1
1     66     102       128.1     女生         1
2     59      65       103.9     男生         0
3     46     117        94.8     女生         0
4     45      79        57.8     男生         0
..   ...     ...         ...    ...       ...
395   72      63        97.1     女生         0
396   22     117       156.7     女生         1
397   31      76       119.0     男生         0
398   36      65        96.3     女生         1
399   38      75       106.3     男生         0

[400 rows x 5 columns]

In [5]:
data["Gender"] = data["Gender"].map({"男生" : 1, "女生": 0})
data

     Age  Weight  BloodSugar  Gender  Diabetes
0     25     119       130.8     NaN         1
1     66     102       128.1     NaN         1
2     59      65       103.9     NaN         0
3     46     117        94.8     NaN         0
4     45      79        57.8     NaN         0
..   ...     ...         ...     ...       ...
395   72      63        97.1     NaN         0
396   22     117       156.7     NaN         1
397   31      76       119.0     NaN         0
398   36      65        96.3     NaN         1
399   38      75       106.3     NaN         0

[400 rows x 5 columns]

In [22]:
from sklearn.model_selection import train_test_split
x = data[["Age", "Weight", "BloodSugar", "Gender"]]
y = data["Diabetes"]

x_train , x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=87)
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
x_train, x_test

(array([[ 47. ,  78. , 112.7,   nan],
        [ 41. ,  79. ,  90.5,   nan],
        [ 28. ,  74. ,  96.4,   nan],
        ...,
        [ 44. ,  53. , 122.2,   nan],
        [ 42. ,  47. ,  69.7,   nan],
        [ 69. , 101. ,  97. ,   nan]]),
 array([[ 74. , 103. , 127.9,   nan],
        [ 73. ,  74. , 106.1,   nan],
        [ 77. ,  65. ,  52. ,   nan],
        [ 22. , 107. , 110. ,   nan],
        [ 31. , 104. ,  98.2,   nan],
        [ 77. ,  47. ,  84.7,   nan],
        [ 50. ,  48. , 103.8,   nan],
        [ 79. ,  87. , 148.4,   nan],
        [ 29. , 106. , 102.8,   nan],
        [ 64. ,  98. , 134. ,   nan],
        [ 27. ,  74. , 115. ,   nan],
        [ 29. ,  81. ,  88.1,   nan],
        [ 45. ,  79. ,  57.8,   nan],
        [ 47. , 106. ,  93.3,   nan],
        [ 60. , 116. , 113.5,   nan],
        [ 63. ,  74. , 102.3,   nan],
        [ 59. ,  65. , 103.9,   nan],
        [ 53. , 107. ,  79. ,   nan],
        [ 52. ,  42. ,  80.5,   nan],
        [ 66. ,  62. ,  72.7,   nan],
        [ 44. , 109. , 105.3,   nan],
        [ 64. ,  62. , 108. ,   nan],
        [ 23. ,  94. , 122. ,   nan],
        [ 52. ,  51. ,  97.9,   nan],
        [ 31. ,  76. , 119. ,   nan],
        [ 28. ,  79. ,  98.1,   nan],
        [ 46. ,  68. , 147. ,   nan],
        [ 24. ,  54. ,  90.8,   nan],
        [ 78. ,  58. , 101.4,   nan],
        [ 67. ,  86. ,  90.3,   nan],
        [ 76. ,  65. ,  96.3,   nan],
        [ 36. , 101. , 110.1,   nan],
        [ 45. ,  63. ,  83.6,   nan],
        [ 46. , 114. , 142.9,   nan],
        [ 27. , 102. ,  92.3,   nan],
        [ 60. ,  48. ,  80.8,   nan],
        [ 29. ,  60. , 115. ,   nan],
        [ 55. ,  63. ,  94.2,   nan],
        [ 66. ,  46. ,  82.8,   nan],
        [ 69. ,  49. ,  75.8,   nan],
        [ 39. , 117. , 129.4,   nan],
        [ 39. , 107. ,  85.6,   nan],
        [ 41. ,  81. , 120.4,   nan],
        [ 42. ,  87. , 149.2,   nan],
        [ 78. ,  81. ,  75.3,   nan],
        [ 25. , 104. ,  91.4,   nan],
        [ 24. , 114. ,  85.3,   nan],
        [ 34. , 106. , 120.2,   nan],
        [ 47. ,  98. , 128. ,   nan],
        [ 40. ,  90. , 123.3,   nan],
        [ 70. ,  54. , 130. ,   nan],
        [ 22. , 110. , 102.8,   nan],
        [ 65. ,  50. ,  77.4,   nan],
        [ 76. ,  58. , 117.6,   nan],
        [ 76. , 104. , 125. ,   nan],
        [ 44. ,  40. ,  81.8,   nan],
        [ 66. ,  70. , 124.3,   nan],
        [ 73. ,  84. , 119.6,   nan],
        [ 76. ,  90. , 101.5,   nan],
        [ 24. ,  80. ,  81.6,   nan],
        [ 32. ,  44. ,  87.8,   nan],
        [ 22. ,  51. , 103.8,   nan],
        [ 28. ,  45. ,  55.2,   nan],
        [ 38. ,  52. ,  72. ,   nan],
        [ 79. ,  82. , 113. ,   nan],
        [ 47. ,  56. ,  90.8,   nan],
        [ 48. , 114. , 125. ,   nan],
        [ 50. , 103. , 111.4,   nan],
        [ 69. ,  88. , 104.1,   nan],
        [ 32. , 114. , 134.2,   nan],
        [ 30. ,  98. ,  77.4,   nan],
        [ 69. ,  94. , 140.9,   nan],
        [ 46. , 113. , 119.7,   nan],
        [ 42. ,  95. , 128.3,   nan],
        [ 66. , 108. , 112.1,   nan],
        [ 70. , 100. , 117.1,   nan],
        [ 21. ,  47. ,  76. ,   nan],
        [ 52. ,  80. ,  89.1,   nan],
        [ 50. , 117. , 139.9,   nan],
        [ 49. ,  72. ,  71.9,   nan]]))

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train

/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

array([[-0.13049114, -0.12021965,  0.35271768,         nan],
       [-0.49202504, -0.07737968, -0.61346817,         nan],
       [-1.27534849, -0.2915795 , -0.35668905,         nan],
       ...,
       [-0.31125809, -1.19121871,  0.76617559,         nan],
       [-0.43176939, -1.44825849, -1.51872338,         nan],
       [ 1.19513315,  0.8650995 , -0.33057592,         nan]])

In [30]:
import numpy as np
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [31]:
w = np.array([1, 2, 3, 4])
b = 1
z = (w*x_train).sum(axis=1) + b
sigmoid(z)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan])